/**
 * Transforms celebrity-results.json into the format needed for the web app.
 * 
 * Usage: bun run scripts/generate-celebrity-data.ts
 * 
 * Input: celebrity-results.json (from recognize-celebrities.ts)
 * Output: lib/celebrity-data.ts (TypeScript file with embedded data)
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

interface CelebrityResult {
  file: string;
  page: number;
  totalPages: number;
  celebrities: {
    name: string;
    confidence: number;
  }[];
}

interface InputData {
  processedAt: string;
  totalImages: number;
  imagesWithCelebrities: number;
  uniqueCelebrities: string[];
  celebrityAppearances: Record<string, { file: string; page: number; confidence: number }[]>;
  results: CelebrityResult[];
}

interface CelebrityAppearance {
  file: string;
  page: number;
  confidence: number;
}

interface Celebrity {
  name: string;
  count: number;
  appearances: CelebrityAppearance[];
}

const ROOT_DIR = join(import.meta.dir, "..");
const INPUT_FILE = join(ROOT_DIR, "celebrity-results.json");
const OUTPUT_FILE = join(ROOT_DIR, "lib", "celebrity-data.ts");

function transformData(input: InputData): Celebrity[] {
  const celebrities: Celebrity[] = [];

  for (const [name, appearances] of Object.entries(input.celebrityAppearances)) {
    // Transform file paths from absolute to relative format
    // From: /Users/.../files/VOL00002/IMAGES/0001/EFTA00003188.pdf
    // To: VOL00002/IMAGES/0001/EFTA00003188.pdf
    const transformedAppearances: CelebrityAppearance[] = appearances.map((app) => {
      // Extract the relative path starting with VOL
      const match = app.file.match(/(VOL\d+\/.*)/);
      const relativePath = match ? match[1] : app.file;
      
      return {
        file: relativePath,
        page: app.page,
        confidence: app.confidence,
      };
    });

    celebrities.push({
      name,
      count: transformedAppearances.length,
      appearances: transformedAppearances,
    });
  }

  // Sort by count descending (most appearances first)
  celebrities.sort((a, b) => b.count - a.count);

  return celebrities;
}

function generateTypeScriptFile(celebrities: Celebrity[], processedAt: string): string {
  return `// Auto-generated by scripts/generate-celebrity-data.ts
// Last updated: ${processedAt}
// Do not edit manually - regenerate with: bun run scripts/generate-celebrity-data.ts

export interface CelebrityAppearance {
  file: string;
  page: number;
  confidence: number;
}

export interface Celebrity {
  name: string;
  count: number;
  appearances: CelebrityAppearance[];
}

export const CELEBRITY_DATA: Celebrity[] = ${JSON.stringify(celebrities, null, 2)};

// Helper to get files for a celebrity (filtered by confidence threshold)
export function getFilesForCelebrity(
  celebrityName: string,
  minConfidence: number = 99
): string[] {
  const celebrity = CELEBRITY_DATA.find((c) => c.name === celebrityName);
  if (!celebrity) return [];

  return celebrity.appearances
    .filter((a) => a.confidence >= minConfidence)
    .map((a) => a.file);
}

// Get celebrities filtered by minimum confidence, sorted by appearance count
export function getCelebritiesAboveConfidence(minConfidence: number = 99): Celebrity[] {
  return CELEBRITY_DATA
    .map((celebrity) => ({
      ...celebrity,
      appearances: celebrity.appearances.filter((a) => a.confidence >= minConfidence),
    }))
    .filter((celebrity) => celebrity.appearances.length > 0)
    .map((celebrity) => ({
      ...celebrity,
      count: celebrity.appearances.length,
    }))
    .sort((a, b) => b.count - a.count);
}

// Build a map of file -> celebrities for quick lookup
export function buildFileToCelebritiesMap(
  minConfidence: number = 99
): Map<string, string[]> {
  const map = new Map<string, string[]>();

  for (const celebrity of CELEBRITY_DATA) {
    for (const appearance of celebrity.appearances) {
      if (appearance.confidence >= minConfidence) {
        const existing = map.get(appearance.file) || [];
        existing.push(celebrity.name);
        map.set(appearance.file, existing);
      }
    }
  }

  return map;
}
`;
}

// Main
console.log("Reading celebrity results from:", INPUT_FILE);

let inputData: InputData;
try {
  const rawData = readFileSync(INPUT_FILE, "utf-8");
  inputData = JSON.parse(rawData);
} catch (error) {
  console.error("Error reading input file:", error);
  process.exit(1);
}

console.log(`Found ${inputData.uniqueCelebrities.length} unique celebrities`);
console.log(`Total images processed: ${inputData.totalImages}`);
console.log(`Images with celebrities: ${inputData.imagesWithCelebrities}`);

const celebrities = transformData(inputData);

console.log("\nCelebrities by appearance count:");
for (const celeb of celebrities.slice(0, 10)) {
  console.log(`  ${celeb.name}: ${celeb.count} appearances`);
}
if (celebrities.length > 10) {
  console.log(`  ... and ${celebrities.length - 10} more`);
}

const tsContent = generateTypeScriptFile(celebrities, inputData.processedAt);
writeFileSync(OUTPUT_FILE, tsContent);

console.log(`\nGenerated: ${OUTPUT_FILE}`);
console.log("Done!");
